name: Run webscraping and commit csv

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * *'  # Exemplo: todo dia meio-dia UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install selenium pandas

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run script
      run: python webscrap.py

    - name: Commit CSV file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add *.csv
        git commit -m "Atualiza CSV - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
