name: Run Selenium Scraper and Commit CSV

on:
  schedule:
    - cron: '0 12 * * *' # Executa todo dia às 12h UTC (9h da manhã no Brasil)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb -y

    - name: Run script
      run: python webscrap.py

    - name: Commit and Push historico.csv
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add output/historico.csv
        git commit -m "chore: update price history ($(date +'%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
        git push
